name = "build/elysium.img"
protective-mbr = true
bootsector = ".chariot-cache/built/tartarus/usr/share/tartarus/mbr.bin"

[[partitions]]
type = "file"
name = "Tartarus"
gpt-type = "54524154-5241-5355-424F-4F5450415254"
file = ".chariot-cache/built/tartarus/usr/share/tartarus/tartarus.sys"

[[partitions]]
type = "fs"
gpt-type = "454C5953-4955-4D52-4F4F-545041525458"
fs-type = "fat32"
size = 64
files = [
    ".chariot-cache/built/kernel/usr/local/share/kernel.elf",
    ".chariot-cache/built/root/root.rdk",
    "support/tartarus.cfg",
    "build/kernelsymbols.txt"
]